
# -*- mode: ruby -*-
# vi: set ft=ruby :


 Vagrant.configure("2") do |config|
 config.vm.box = "bento/ubuntu-18.04"
 config.winrm.timeout =   1800 # 30 minutes
 config.vm.boot_timeout = 1800 # 30 minutes
 required_plugins = []
 required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

   
   
config.vm.provision "shell", inline: <<-SHELL
     wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
     dpkg -i puppet5-release-$(lsb_release -cs).deb
     apt-get -qq update
     apt-get install -y puppet-agent

   SHELL

 config.vm.provision "puppet" do |puppet|
  puppet.manifests_path = "/etc/project_root/environments/test/manifests/"
  puppet.manifest_file = "default.pp"

end
end
